### ISSUE TITLE
Power plot when sample size depends on multiple designer arguments

### ISSUE THREAD

**Issue by clabima** [DeclareDesign/shiny#14]
The sample size of cluster_sampling_designer() and block_cluster_two_arm_designer() depends on multiple arguments set within shiny app. Currently the inspector power plot has a manual fix for these designers but requires a more permanent solution involving standardizing argument names.

**Comment by jaspercooper** [comment]
I have an alternative proposal for how this tab works.

Right now the power plot tab privileges N. This creates problems in at least two cases:
  - The case @clabima mentions, where the N is created from two or more other arguments (N_per_x, N_per_y)
  - The case where the designer / shiny_arguments do not have N

I propose we have one power plot for every shiny_argument (remember a designer might have 10 arguments in its formals but only 3 of these may be specified as shiny_arguments using the attributes). Each power plot will be a curve that varies that argument across its whole range, holding the other parameters set at the level the user has specified in "design_parameters".

For example, imagine the following designer:
```r
designer <- function(ate = 1, sd = 1, non_compliance_rate = 0){...}
attributes(designer, "shiny_arguments") <- list(ate = 1:3, sd = 0:2)
```
Note that non_compliance_rate doesn't make it into the inspector here because its range is not specified as a shiny_argument.

Let's imagine the user chooses an ate of 2 and an sd of 1 in the dropdown menus. When the user looks at the power plots tab, they will see:
  - a power curve that goes over ate = 1,2,3 holding sd constant at 1
  - a power curve that goes over sd = 0,1,2 holding ate constant at 2

Then if they change the ate to 3, the ate plot won't change, but now the power curve for sd will go over the same range of sds, but it will show different power because the ate is held constant at 3.

Advantages:
 -  totally agnostic to parameters
 - gives you a power curve for any possible parameter space
 - doesn't generate N_shiny_args^2 plots

I think we should have separate bias and coverage tabs that do the exact same thing.

Interested to hear thoughts @macartan @graemeblair @acoppock @medinali @clabima

**Comment by nfultz** [comment]
Would this be faceted by the parameter? Or does it require ui to choose the
active plot?

**Comment by jaspercooper** [comment]
I envisioned it being faceted by parameter with x scales free -- do you foresee any potential issues with either approach @nfultz?
